# Generated by Django 6.0.2 on 2026-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_student_remove_news_content_remove_news_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
