# Generated by Django 6.0.2 on 2026-03-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='Approved', max_length=20),
        ),
    ]
