# Generated by Django 6.0.2 on 2026-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_gallery_admission_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='admission/aadhar/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='admission/birth/'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admission/photo/'),
        ),
    ]
