# Generated by Django 6.0.2 on 2026-03-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_admission_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('about_text', models.TextField(blank=True, null=True)),
                ('welcome_text', models.TextField(blank=True, null=True)),
                ('principal_image', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('principal_text', models.TextField(blank=True, null=True)),
                ('map_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
