# Generated by Django 6.0.2 on 2026-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_eventimage_websitecontent_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
        migrations.DeleteModel(
            name='WebsiteContent',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='date',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=None, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
