# Generated by Django 6.0.2 on 2026-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_livenews_delete_eventimage_delete_websitecontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livenews',
            name='text',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
