# Generated by Django 6.0.2 on 2026-03-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_remove_livenews_text_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenews',
            name='text',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
