# Generated by Django 6.0.2 on 2026-03-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0013_livenews_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome To Our School', max_length=500)),
                ('subtitle', models.CharField(default='Bright Future Starts Here', max_length=700)),
                ('slide1', models.ImageField(upload_to='hero/')),
                ('slide2', models.ImageField(upload_to='hero/')),
                ('slide3', models.ImageField(upload_to='hero/')),
            ],
        ),
    ]
