# Generated by Django 6.0.2 on 2026-03-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0014_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_desc', models.TextField()),
                ('principal_image', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('principal_p1', models.TextField()),
                ('principal_p2', models.TextField()),
                ('principal_p3', models.TextField()),
                ('principal_name', models.CharField(max_length=100)),
                ('manager_image', models.ImageField(blank=True, null=True, upload_to='manager/')),
                ('manager_p1', models.TextField()),
                ('manager_p2', models.TextField()),
                ('manager_p3', models.TextField()),
                ('manager_name', models.CharField(max_length=100)),
            ],
        ),
    ]
