# Generated by Django 6.0.2 on 2026-03-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0015_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='herosection',
            name='slide1',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='slide2',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='slide3',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
