# Generated by Django 6.0.2 on 2026-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_delete_about_alter_herosection_slide1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('description', models.TextField()),
            ],
        ),
    ]
