# Generated by Django 6.0.2 on 2026-03-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0020_campusevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
