# Generated by Django 6.0.2 on 2026-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0021_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_link', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
